export const uiStrings = {
  brand:        { fr: "Tableau de bord des villes", en: "World Cities Dashboard" },
  progression:  { fr: "Progression", en: "Progress" },
  locked:       { fr: "Verrouillé — termine l'étape précédente", en: "Locked — finish the previous step" },
  showSolution: { fr: "Afficher la correction", en: "Show solution" },
  hideSolution: { fr: "Masquer la correction", en: "Hide solution" },
  runHint:      { fr: "Le résultat se met à jour automatiquement.", en: "The preview updates automatically." },
  quizValidate: { fr: "Valider", en: "Submit" },
  quizRetry:    { fr: "Réessayer", en: "Try again" },
  quizPassed:   { fr: "Réussi ! Étape suivante débloquée.", en: "Passed! Next step unlocked." },
  quizFailed:   { fr: "Pas encore — réessaie pour débloquer la suite.", en: "Not yet — try again to unlock." },
  next:         { fr: "Étape suivante", en: "Next step" },
  prev:         { fr: "Étape précédente", en: "Previous step" },
  teacherUnlock:{ fr: "Tout déverrouiller (prof)", en: "Unlock all (teacher)" },
  reset:        { fr: "Réinitialiser ma progression", en: "Reset my progress" },
  blockNeed:    { fr: "Le besoin", en: "The need" },
  blockDiscover:{ fr: "Découverte", en: "Discover" },
  blockExplain: { fr: "Explication", en: "Explanation" },
  blockExample: { fr: "Exemple", en: "Example" },
  blockExercise:{ fr: "Exercice", en: "Exercise" },
  blockApply:   { fr: "Dans le projet", en: "In the project" },
  blockQuiz:    { fr: "Quiz", en: "Quiz" },
  optionalChallenge: { fr: "Défi optionnel", en: "Optional challenge" }
};
